project_id = "ynlnrvuqypmwpevabtdc"

[functions.check-hotel-availability]
verify_jwt = false

[functions.fetch-hotel-data]
verify_jwt = false

[functions.validate-voucher]
verify_jwt = false

[functions.test-hotel-availability]
verify_jwt = false