name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-hotel-availability:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
        
    - name: Deploy test function
      run: |
        supabase functions deploy test-hotel-availability
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        
    - name: Run integration tests
      run: |
        # Get the function URL
        SUPABASE_URL=$(supabase status --output json | jq -r '.api.url')
        FUNCTION_URL="${SUPABASE_URL}/functions/v1/test-hotel-availability"
        
        echo "Running tests against: $FUNCTION_URL"
        
        # Run the tests
        response=$(curl -s -X POST "$FUNCTION_URL" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}")
        
        echo "Test response: $response"
        
        # Parse the response and check if tests passed
        success=$(echo "$response" | jq -r '.success')
        if [ "$success" != "true" ]; then
          echo "Integration tests failed!"
          echo "$response" | jq '.'
          exit 1
        fi
        
        echo "All integration tests passed!"
        echo "$response" | jq '.summary'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        
    - name: Cleanup
      if: always()
      run: |
        # Clean up test function if needed
        echo "Test completed"
