name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-hotel-availability:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
        
    - name: Deploy test function
      run: |
        supabase functions deploy test-hotel-availability
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        
    - name: Run integration tests
      run: |
        # Set environment variables for the test script
        export SUPABASE_URL="https://ynlnrvuqypmwpevabtdc.supabase.co"
        export SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}"
        export SCRAPERAPI_KEY="${{ secrets.SCRAPERAPI_KEY }}"
        
        echo "Running complete integration tests..."
        
        # Run the complete integration test suite
        npm run test:integration-complete
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        
    - name: Cleanup
      if: always()
      run: |
        # Clean up test function if needed
        echo "Test completed"
